package manager;

import java.util.List;

import javax.swing.JOptionPane;

import com.google.cloud.firestore.QueryDocumentSnapshot;

import accesoDatos.Reader;
import objects.Usuario;

public class Login {
	
	public static Usuario currentUser =null;
	

	public boolean verifyUser(String user, String password) throws Exception {
		
		List<QueryDocumentSnapshot> usuarios = new Reader().findUsuariosFirebase();
		
		return findUserList(user, password, usuarios);
		
	}

	/**
	 * We are using email as a user for validation,  we could add also the autogenerated  user id, as it is unique I believe
	 * 
	 * @param user user inserted in a textfiel in login panel
	 * @param passwordinserted in a textfiel in login panel
	 * @param usuarios list of usuarios retirve from firebase
	 * @return
	 * @throws Exception 
	 */
	private boolean findUserList(String email, String password, List<QueryDocumentSnapshot> usuarios) throws Exception {

		for (QueryDocumentSnapshot usuario : usuarios) {
		   
		    if(usuario.getString("email").equalsIgnoreCase(email)  && usuario.getString("password").equals(password))
		    {  
		    	currentUser = new UserInfo().getUserInfor(email);
		    	System.out.println("findUserList Login "+currentUser.toString());
		  		    return true;
		    }
		}
		return false;
	}

	private void loadCurrentUser(QueryDocumentSnapshot usuario) {
		//currentUser = new Usuario();


		currentUser.setName(usuario.getString("name"));
		currentUser.setSurname(usuario.getString("surname"));
		currentUser.setTrainer(usuario.getBoolean("isTrainer"));
		currentUser.setLevel(usuario.getDouble("level").intValue());
		currentUser.setEmail(usuario.getString("email"));
		
		
	}
	
}
